version: '3'
services:
  dynamodb.local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - ./db:/home/dynamodblocal/db
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/home/dynamodblocal/db"]